### ISSUE TITLE
here you meant "values", correct?

### ISSUE THREAD

**Issue by iranroman** [vackosar/vackosar.github.io#2]
https://github.com/vackosar/vackosar.github.io/blob/dd7455698beb35597d044e3f149f669c8948e94f/_posts/2021-12-28-cross-attention-in-transformer-architecture.md?plain=1#L55

This line should read:

"Apply values to the attention matrix"

Otherwise I'm very confused.

**Comment by vackosar** [comment]
That is correct! Thank you.
